server:
  port: 8083

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student
          uri: lb://student
          predicates:
            - Path=/student/**
        - id: school
          uri: lb://school
          predicates:
            - Path=/school/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true